# docker-compose.yml
services:
  postgres:
    image: postgres:15-alpine
    container_name: sq_postgres
    restart: unless-stopped
    networks:
      - nginx_proxy
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: yourStrongPassword   # 与下方保持一致
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 30s
      timeout: 10s
      retries: 3

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # JVM 参数、时区、中文界面全部保留
      - JAVA_OPTS=-Duser.language=zh -Xmx4G -Xms2G
      - TZ=Asia/Shanghai
      # 关键：换成 PostgreSQL
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=yourStrongPassword
    networks:
      - nginx_proxy
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_extensions:/opt/sonarqube/extensions
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  nginx_proxy:
    external: true
