services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Duser.language=zh -Xmx4G -Xms2G
      - TZ=Asia/Shanghai
      - SONAR_JDBC_URL=jdbc:mariadb://mariadb:3306/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=yourStrongPassword
    networks:
      - nginx_proxy
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_extensions:/opt/sonarqube/extensions
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  nginx_proxy:
    external: true