version: '2'
services:
  web:
    image: gitea/gitea:latest
    container_name: gitea
    volumes:
      - ./data:/data
    expose:
      - 3000
      - 22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=${MYSQL}:3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
    restart: always
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true