services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    # ports:
    #   - "8080:80"
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./settings.json:/settings.json
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    restart: unless-stopped
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true