version: "3"

services: 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    volumes:
     - /sessions
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true