services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=${TIME_ZONE}
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"
    pid: "host"
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"