version: "3"

services: 
  ci:
    image: jenkinsci/blueocean
    container_name: "jenkinsci"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/jenkins/jenkins-data:/var/jenkins_home
    expose: 
      - 8080 
      - 50000
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true