services:
  db:
    image: mariadb
    restart: unless-stopped
    container_name: mariadb
    # ports:
    #   - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - TZ=${TIME_ZONE}
      # - MARIADB_ROOT_HOST=% if you want remote connect mariadb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
