version: '3'

services:

  db:
    image: mysql:5.5
    restart: always
    container_name: global_mysql
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - TZ=${TIME_ZONE}
      # - MYSQL_ROOT_HOST=% if you want remote connect mysql
    volumes:
      -  ./mysql_data:/var/lib/mysql
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
